infinispan-ear-webapp/src/main/java/org/lduriez/jcache/infinispan/controller/CDICacheController.java
package org.lduriez.jcache.infinispan.controller;

import java.util.List;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.lduriez.jcache.infinispan.business.CityService;
import org.lduriez.jcache.infinispan.business.CountryService;
import org.lduriez.jcache.model.CityDto;
import org.lduriez.jcache.model.CountryDto;

/**
 * Controller for CDI cache testing
 *
 */
@Named("CDICacheController")
@RequestScoped
public class CDICacheController {

	@Inject
	private CityService cityService;
	
	@Inject
	private CountryService countryService;
	
	/**
	 * Clear city cache
	 * 
	 * @return "OK"
	 */
	public String getClearCityCache() {
		cityService.clearCityCache();
		return "OK";
	}
	
	/**
	 * Fetch cities from datastore
	 * 
	 * @return all cities, unsorted
	 */
	public List<CityDto> getCities() {
		return cityService.getCities();
	}
	
	/**
	 * Fetch countries from datastore
	 * 
	 * @return all countries, unsorted
	 */
	public List<CountryDto> getCountries() {
		return countryService.getCountries();
	}
	
	public String getCityCacheInfo() {
		return cityService.getCacheInfo();
	}
}

infinispan-ear-webapp/src/main/webapp/main/infinispan-cities.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Cities</title>
</head>
<body>
	<table>
		<c:forEach items="${CDICacheController.cities}" var="city">
			<tr>
				<td>${city.name}</td>
			</tr>
		</c:forEach>
	</table>
	<br>
	City cache info
	<br>
	Size : ${CDICacheController.cityCacheInfo}
</body>
</html>

infinispan-ear-webapp/src/main/webapp/main/infinispan-countries.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Countries</title>
</head>
<body>
	<table>
		<c:forEach items="${CDICacheController.countries}" var="country">
			<tr>
				<td>${country.name}</td>
			</tr>
		</c:forEach>
	</table>
</body>
</html>

infinispan-ear-webapp/src/main/webapp/main/infinispan-modify-cities.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Add city</title>
</head>
<body>
Clear city cache : ${CDICacheController.clearCityCache}
</body>
</html>

infinispan-ear-webapp/src/main/webapp/main/infinispan.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>City cache size</title>
</head>
<body>
City cache size : ${CDICacheController.cityCacheSize}
</body>
</html>